schema_version = "1.0.0"

id = "Ieslibrary4Blender"
version = "1.0.3"
name = "Ieslibrary Integration"
tagline = "Import IES from a single URL from ieslibrary.com"
maintainer = "Jürgen Furrer <juergen@swisscode.sk>"
type = "add-on"

website = "https://github.com/juergenfurrer/Ieslibrary4Blender"

tags = ["Lighting", "Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
network = "Need to download the IES files from ieslibrary.com"
files = "Store the downloaded IES-Files to disk"
clipboard = "Automatically scrap the copied url as a new IES-light"
